"""Migra uma cópia SQLite do Gestor para PostgreSQL.

Uso:
  DATABASE_URL='postgresql://...' python3 scripts/migrate_sqlite_to_postgres.py \
      /caminho/para/pms.sqlite3

O script exige um banco PostgreSQL vazio. Ele não altera o SQLite de origem e
interrompe ao encontrar tabelas já existentes no destino.
"""
from __future__ import annotations

import argparse
import os
import re
import sqlite3
import sys
from pathlib import Path


def postgres_ddl(sql: str) -> str:
    """Converte o subconjunto SQLite usado pelo projeto para PostgreSQL."""
    ddl = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
        flags=re.I,
    )
    ddl = re.sub(r"\bCOLLATE\s+NOCASE\b", "", ddl, flags=re.I)
    ddl = re.sub(r"\bBLOB\b", "BYTEA", ddl, flags=re.I)
    timestamp_columns = (
        "applied_at|atualizado_em|avaliado_em|concluido_em|criado_em|"
        "expira_em|registrado_em|ultimo_login|updated_at"
    )
    ddl = re.sub(
        rf"\b({timestamp_columns})\s+TEXT\b",
        r"\1 TIMESTAMPTZ",
        ddl,
        flags=re.I,
    )
    # json_valid é uma função do SQLite. O conteúdo continua como TEXT e o
    # migrador valida JSON antes de inseri-lo.
    ddl = re.sub(r"\s+CHECK\s*\(json_valid\(data\)\)", "", ddl, flags=re.I)
    return ddl


def source_objects(source: sqlite3.Connection):
    return source.execute(
        """SELECT type,name,sql FROM sqlite_master
           WHERE type IN ('table','index','view') AND name NOT LIKE 'sqlite_%'
           ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'index' THEN 2 ELSE 3 END, rowid"""
    ).fetchall()


def table_order(source: sqlite3.Connection, tables: list[str]) -> list[str]:
    """Ordena pais antes de filhos para manter as referências na criação e carga."""
    pending = set(tables)
    dependencies = {
        table: {row[2] for row in source.execute(f'PRAGMA foreign_key_list("{table}")') if row[2] in pending}
        for table in tables
    }
    ordered = []
    while pending:
        ready = sorted(table for table in pending if not (dependencies[table] & pending))
        if not ready:
            raise RuntimeError("Dependência circular encontrada entre: " + ", ".join(sorted(pending)))
        ordered.extend(ready)
        pending.difference_update(ready)
    return ordered


def insert_rows(source: sqlite3.Connection, target, table: str) -> int:
    columns = [row[1] for row in source.execute(f'PRAGMA table_info("{table}")')]
    if not columns:
        return 0
    quoted = ", ".join(f'"{column}"' for column in columns)
    placeholders = ", ".join("%s" for _ in columns)
    command = f'INSERT INTO "{table}" ({quoted}) VALUES ({placeholders})'
    rows = source.execute(f'SELECT {quoted} FROM "{table}"')
    count = 0
    with target.cursor() as cursor:
        for row in rows:
            cursor.execute(command, tuple(row))
            count += 1
    return count


def reset_sequences(target, tables: list[str]):
    with target.cursor() as cursor:
        for table in tables:
            cursor.execute(
                """SELECT is_identity FROM information_schema.columns
                   WHERE table_schema='public' AND table_name=%s AND column_name='id'""",
                (table,),
            )
            row = cursor.fetchone()
            if row and row[0] == "YES":
                cursor.execute(
                    f'''SELECT setval(pg_get_serial_sequence(%s, 'id'),
                                      COALESCE(MAX(id), 1), MAX(id) IS NOT NULL)
                         FROM "public"."{table}"''',
                    (table,),
                )


def migrate(source_path: Path, database_url: str):
    try:
        import psycopg
    except ImportError as error:
        raise SystemExit("Instale as dependências: pip install -r requirements.txt") from error
    if not source_path.is_file():
        raise SystemExit(f"Banco SQLite não encontrado: {source_path}")
    source = sqlite3.connect(source_path)
    source.row_factory = sqlite3.Row
    objects = source_objects(source)
    table_sql = {name: sql for kind, name, sql in objects if kind == "table"}
    tables = table_order(source, list(table_sql))
    with psycopg.connect(database_url) as target:
        with target.cursor() as cursor:
            cursor.execute("SELECT tablename FROM pg_tables WHERE schemaname='public'")
            existing = [row[0] for row in cursor.fetchall()]
            if existing:
                raise RuntimeError("O PostgreSQL de destino precisa estar vazio. Tabelas encontradas: " + ", ".join(existing))
            for table in tables:
                cursor.execute(postgres_ddl(table_sql[table]))
        counts = {table: insert_rows(source, target, table) for table in tables}
        with target.cursor() as cursor:
            for kind, name, sql in objects:
                if kind == "index":
                    cursor.execute(postgres_ddl(sql))
                elif kind == "view":
                    # PostgreSQL exige numeric para ROUND com precisão.
                    view = re.sub(r"ROUND\((SUM\([^)]*\)|SUM\(COALESCE\([^)]*\)\)),\s*(\d+)\)", r"ROUND((\1)::numeric, \2)", sql)
                    cursor.execute(view)
            cursor.execute("CREATE UNIQUE INDEX usuarios_username_ci ON usuarios (LOWER(username))")
        reset_sequences(target, tables)
    source.close()
    return counts


def main():
    parser = argparse.ArgumentParser(description="Migra SQLite do Gestor para PostgreSQL")
    parser.add_argument("sqlite_database", type=Path)
    args = parser.parse_args()
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        raise SystemExit("Defina DATABASE_URL com a conexão PostgreSQL antes de executar.")
    counts = migrate(args.sqlite_database, database_url)
    print("Migração concluída:")
    for table, count in counts.items():
        print(f"- {table}: {count}")


if __name__ == "__main__":
    main()
